server:
  port: 8090

token:
  header: Authorization
  secret:
  expireTime: 480

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.10.10.102:3307/publisher?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: eLe9Vrg98hFdhhB

springdoc:
  packages-to-scan:
    - top.watilion.publisher.controller
  paths-to-match:
    - /system/**
    - /v1

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n"
  level:
    top.watilion.publisher.controller.UserController: INFO
  file:
    name: ${user.dir}/logs/publisher.log

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-not-delete-value: 0